### ISSUE TITLE
6章のparserの本文中に記載の実装の誤りについて

### ISSUE THREAD

**Issue by tawashichan** [ytakano/rust_zero#1]
誤植の報告になります。

p141のサンプルコードですが,Errを返す部分でParseErrorをBoxで包んでいますが,不要であると思われます(Boxで包むと型が合わなくなる)
github上のソースコードにおける対応箇所はBoxで包まない実装になっています(下記が一例になります)。
https://github.com/ytakano/rust_zero/blob/master/ch06/regex/src/engine/parser.rs#L106

**Comment by ytakano** [comment]
ありがとうございます！

正誤表のページに追記させて頂きました。
https://github.com/ytakano/rust_zero/blob/master/errata.md
