### ISSUE TITLE
第3章 p68 「ライフタイム指定子」のコードのコンパイルエラー

### ISSUE THREAD

**Issue by tyahha** [ytakano/rust_zero#10]
「ゼロから学ぶRust」楽しく読み進めています。

コンパイルエラーになるサンプルコードがありましたので報告いたします。

第3章 p68 「ライフタイム指定子」のコードの最初の2行が次のように記載されています。

```rust
let a: i32 = 10;
let b: &i32 = &b;
```

上記だと`error[E0425]: cannot find value `b` in this scope`のようなエラーになりますので正しくは次の通りだと考えたのですがいかがでしょうか。

```rust
let a: i32 = 10;
let b: &i32 = &a;
```

**Comment by ytakano** [comment]
ありがとうございます！
正誤表に追記しました。
https://github.com/ytakano/rust_zero/blob/master/errata.md
