### ISSUE TITLE
第3章のp75の本文について

### ISSUE THREAD

**Issue by tomiy-0x62** [ytakano/rust_zero#12]
第1刷の誤植の報告です。

p75に
> XYのxフィールドの値を2倍した値をyフィールドに追加したいとしよう。

とありますが、コードでは2倍した値ではなく2乗した値をyフィールドに追加しています。

```rust
for elm in xy.x.iter() {
    y.push(*elm * *elm);
 }
```

**Comment by ytakano** [comment]
https://github.com/ytakano/rust_zero/blob/master/errata.md
ありがとうございます！
正誤表を更新しました。
