### ISSUE TITLE
第4章のp90のデシリアライズのコードについて

### ISSUE THREAD

**Issue by tomiy-0x62** [ytakano/rust_zero#13]
第1刷の誤植の報告です。

p90のYAMLからデシリアライズするコードおよびGithub上のサンプルコードについてですが、
https://github.com/ytakano/rust_zero/blob/9c971a1a575e216db13e5380f262044b5d7cf874/ch04/serialize/src/main.rs#L46

本来`&yml`となるべき箇所が`&js`となっています。

**Comment by ytakano** [comment]
ありがとうございます！
正誤表に追記し、ソースコードを修正しました。
