### ISSUE TITLE
第３章p72のtypo

### ISSUE THREAD

**Issue by speed1313** [ytakano/rust_zero#14]
楽しく読ませていただいております！
細かなミスですが, 
第一刷p72, 3.4.2の上から10行目

> 可変参照は、参照カウントと変数の状態遷移図で考察できる。本項では、可燃参照の

の可燃参照が可変参照のtypoと思われます.

**Comment by ytakano** [comment]
https://github.com/ytakano/rust_zero/blob/master/errata.md
ありがとうございます！正誤表を更新しました。
可燃参照とは…
