### ISSUE TITLE
p88の図4.3のjsonのtypo

### ISSUE THREAD

**Issue by speed1313** [ytakano/rust_zero#15]
第一刷p88の図4.3のjsonが
> {"top": {"left": {"left": "left", "right": "leaf},
> "right": {"left: "leaf", "right": "leaf"}}

となっていますが, leaf及びleftの"閉じ忘れ, }閉じ忘れがあるように思われます.
> {"top": {"left": {"left": "left", "right": "leaf"},
> "right": {"left": "leaf", "right": "leaf"}}}

が正しいのではないかと思いました.

**Comment by ytakano** [comment]
こちらも、ありがとうございます。
正誤表のページに追記しました！
https://github.com/ytakano/rust_zero/blob/master/errata.md
