### ISSUE TITLE
誤字／誤植？

### ISSUE THREAD

**Issue by yorozuya-benkyodo** [ytakano/rust_zero#16]
22ページ1行目の「...とすることで、４つの配列を持つ配列の値を定義できる。」という文は、何かおかしくありませんか？

**Comment by ytakano** [comment]
ありがとうございます。
「4つの値を持つ配列を定義できる」が正しいです。正誤表に追記させて頂きました。
https://github.com/ytakano/rust_zero/blob/master/errata.md
