### ISSUE TITLE
3.5 借用と排他制御の類似性: 文中の「開放」という用語について

### ISSUE THREAD

**Issue by hmarui66** [ytakano/rust_zero#19]
Kindle 2023年3月11発行版にて。

> ヒープメモリに確保した領域を開放する。

という記述が(2箇所)ありますが、他の箇所では「解放」という用語が使われています。
誤字の可能性があるかと思い、ご報告いたしました。

**Comment by ytakano** [comment]
ありがとうございます！
こちら正誤表に追記しました。
https://github.com/ytakano/rust_zero/blob/master/errata.md
