### ISSUE TITLE
図2.6 リンクリストの例

### ISSUE THREAD

**Issue by psyto** [ytakano/rust_zero#2]
図2.6で、２番目（中央）のノード、dataの値は40は誤植で10が正解かと思います。

素晴らしい書籍を執筆頂き、ありがとうございます。

**Comment by ytakano** [comment]
ありがとうございます。そういって頂けると励みになります！

正誤表のページに追記させて頂きました。
https://github.com/ytakano/rust_zero/blob/master/errata.md
