### ISSUE TITLE
6.3.1 パーサ: ParseError の Display トレイト実装のメッセージについて

### ISSUE THREAD

**Issue by hmarui66** [ytakano/rust_zero#20]
Kindle 2023年3月11発行版にて。

https://github.com/ytakano/rust_zero/blob/b2916d77fc53dce08a9035b9a103c7134e8776cc/ch06/regex/src/engine/parser.rs#L23

上記のメッセージ中に含む「espace」は「escape」の誤記かと思いますので、ご報告いたします。

**Comment by ytakano** [comment]
ありがとうございます！
ソースコードを修正し、正誤表にも追記しました。
https://github.com/ytakano/rust_zero/blob/master/errata.md
