### ISSUE TITLE
3.4.2項 可変参照としての借用

### ISSUE THREAD

**Issue by ultimatile** [ytakano/rust_zero#23]
すでに指摘されているP. 75の上のソースコードの下から2行目の `*elm * *elm`→`*elm + *elm`ですが, 同ページの下のソースコードの下から2行目も同様に`*elm * *elm`→`*elm + *elm`となるのではないでしょうか?

**Comment by ytakano** [comment]
ありがとうございます！
誤植ありまして申し訳ありません。こちら、以下の正誤表に記載しておりますので、ご確認ください。
https://github.com/ytakano/rust_zero/blob/master/errata.md
