### ISSUE TITLE
ch06のmain.rsのドキュメントのtypoについて

### ISSUE THREAD

**Issue by hmarui66** [ytakano/rust_zero#24]
https://github.com/ytakano/rust_zero/blob/cc84ff7de7d7ba9b74f045db347bc54bf9750082/ch06/regex/src/main.rs#L26

「の」が抜けているようでしたので、ご報告いたします。

```diff
- いずれかにマッチした場合に、その行がマッチしたもとみなす。
+ いずれかにマッチした場合に、その行がマッチしたものとみなす。
```

**Comment by ytakano** [comment]
ありがとうございます。修正しました。
