### ISSUE TITLE
p75: 「構造体のフィールドを借用しコンパイルエラーとなる例」について

### ISSUE THREAD

**Issue by mosmos21** [ytakano/rust_zero#3]
素晴らしい書籍の執筆ありがとうございます。
書籍を読み進めるにあたり、誤植の発見とサンプルコードについての挙動の疑問がありましたので質問させてください。

## 誤植について

該当コード
```
for elm in xy.x.iter() {
    y.push(*elm * *elm);
}
```

以下が正しいかと思われます。ご確認お願いします。
```
for elm in xy.x.iter() {
    xy.y.push(*elm * *elm);
}
```

## コンパイルエラーについて

サンプルコードをコンパイルしてみたところエラーが出ませんでした。([playgroundのリンク](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=a9c19883e2eb987d27349b44c04a2e7e))
rustのバージョンアップにより挙動が変わっている可能性が考えられますので、ご確認お願います。

**Comment by ytakano** [comment]
ありがとうございます！
たしかに、ここの説明はおかしい気がします。
少し考えます。

**Comment by ytakano** [comment]
以下のようなコードを想定していました。もう少し良い例がないか、考えます。

```rust
#[derive(Debug)]
struct XY {
    x: Vec<i32>,
    y: Vec<i32>,
}

fn main() {
    let mut xy = XY {
        x: vec![1, 2, 3],
        y: Vec::new(),
    };
    
    xy.update(&xy.x); // コンパイルエラー
    
    println!("{:?}", xy);
}

impl XY {
    fn update(&mut self, x: &[i32]) {
        for elm in x.iter() {
            self.y.push(*elm * *elm);
        }
    }
}
```
https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=a4467e3c859349c72a0f80aa101c9f0c

**Comment by ytakano** [comment]
こちら正誤表に記載させて頂きました。
ありがとうございます。

**Comment by ytakano** [comment]
もう少し良い例を思いついたので、正誤表をアップデートしました。
ご指摘ありがとうございます。

[正誤表](https://github.com/ytakano/rust_zero/blob/master/errata.md#342%E9%A0%85p75%E6%A7%8B%E9%80%A0%E4%BD%93%E3%81%AE%E3%83%95%E3%82%A3%E3%83%BC%E3%83%AB%E3%83%89%E3%82%92%E5%80%9F%E7%94%A8%E3%81%97%E3%82%B3%E3%83%B3%E3%83%91%E3%82%A4%E3%83%AB%E3%82%A8%E3%83%A9%E3%83%BC%E3%81%A8%E3%81%AA%E3%82%8B%E4%BE%8B)

**Comment by jl1nie** [comment]
ハマりがちなポイントなので大変参考になりました。
この例のエラーが分配束縛などでどのように解消できるか、修正結果も正誤表に追加していただけないでしょうか。
