### ISSUE TITLE
表現の変更提案

### ISSUE THREAD

**Issue by avtomat2023** [ytakano/rust_zero#30]
2.2.15 マルチスレッド の、2 チャンネル の最後の段落ですが、「受信は1スレッドからしかできない。複数スレッドから受信したい場合は、」は「受信は1スレッドでしかできない。複数スレッドで受信したい場合は、」に変更したほうがよいと思います。
「複数スレッドから受信」という表現だと、複数のスレッドから送信されたデータを受信する、という意味に取れてしまいます。

**Comment by ytakano** [comment]
ありがとうございます。
修正できる機会があれば、修正したいと思います。
