### ISSUE TITLE
201頁、課題7.4 ③について

### ISSUE THREAD

**Issue by Ukuma012** [ytakano/rust_zero#33]
「openシステムコールのラッパであるnix::unistd::openを用いるとできる」とありますが、これはnix::fcntl::openではないでしょうか？

https://docs.rs/nix/latest/nix/fcntl/fn.open.html

**Comment by ytakano** [comment]
ありがとうございます。
ご指摘通り、`nix::fcntl::open`です。
Errataに追記しました。
https://github.com/ytakano/rust_zero/commit/24d211039b3ed3720d1b5ba46bf2b515c19b1ee7
